import Foundation

// MARK: - FailureTypes Enum
enum FailureTypes: Int, CaseIterable, Codable {
    case none                                        = -1
    case imbalance                                   = 0
    case misalignment                                = 1
    case looseness                                   = 2
    case rotationalLooseness                         = 3
    case bearingWear                                 = 4
    case gearWear                                    = 5
    case lubricantContamination                      = 6
    case cavitation                                  = 7
    case impellerWear                                = 8
    case rubbing                                     = 9
    case electrical                                  = 10
    case resonance                                   = 11
    case beltFailure                                 = 12
    case chainFailure                                = 13
    case rotorProblem                                = 14
    case fatigueCracks                               = 15
    case componentFracture                           = 16
    case gearToothBreakage                           = 17
    case keywayFailure                               = 18
    case bushingWear                                 = 19
    case couplingFailure                             = 20
    case beltSlippage                                = 21
    case gearboxOverheating                          = 22
    case rotorDamage                                 = 23
    case sealLeakage                                 = 24
    case structuralDeformation                       = 25
    case clutchWear                                  = 26
    case pistonWear                                  = 27
    case valveSticking                               = 28
    case camshaftWear                                = 29
    case highVibration                               = 30
    case excessiveShockLoading                       = 31
    case vibrationInducedLoosening                   = 32
    case torsionalVibration                          = 33
    case axialVibration                              = 34
    case highTemperature                             = 35
    case overheating                                 = 36
    case thermalExpansionIssues                      = 37
    case thermalFatigue                              = 38
    case electricalComponentsInsulationDegradation   = 39
    case heatExchangerFouling                        = 40
    case lubricantDegradation                        = 41
    case insufficientLubrication                     = 42
    case excessiveLubrication                        = 43
    case oilOxidation                                = 44
    case greaseClogging                              = 45
    case lubricantLeaks                              = 46
    case electricalShortCircuits                     = 47
    case insulationFailure                           = 48
    case motorOverheating                            = 49
    case powerSupplyFluctuations                     = 50
    case motorsBearingCurrentDamage                  = 51
    case circuitBoardFailure                         = 52
    case sensorMalfunction                           = 53
    case controlSystemFailures                       = 54
    case corrosion                                   = 55
    case dustIngress                                 = 56
    case waterIngress                                = 57
    case chemicalAttack                              = 58
    case particulateContamination                    = 59
    case biologicalGrowth                            = 60
    case contaminantsAbrasiveWear                    = 61
    case overloading                                 = 62
    case underloading                                = 63
    case incorrectOperatingSpeed                     = 64
    case improperStartupShutdownProcedures           = 65
    case frequentCycling                             = 66
    case poorMaintenancePractices                    = 67
    case materialCorrosion                           = 68
    case brittleFracture                             = 69
    case ductileFracture                             = 70
    case creepDeformation                            = 71
    case stressCorrosionCracking                     = 72
    case hydrogenEmbrittlement                       = 73
    case processVariations                           = 74
    case inadequateProcessControl                    = 75
    case thermalShock                                = 76
    case pressureSurges                              = 77
    case flowBlockages                               = 78
    case pumpCasingCracks                            = 79
    case fanBladeCracks                              = 80
    case millLiningWear                              = 81
    case pressDieWear                                = 82
    case filterClogging                              = 83
    case valveSealFailure                            = 84
    case sensorDrift                                 = 85
    case actuatorSticking                            = 86
    case controlSystemsSoftwareGlitches              = 87
    case humanErrors                                 = 88
    case improperCalibration                         = 89
    case vibrationInducedElectricalNoise             = 90
    case resonantFrequencyChanges                    = 91
    case anchoringFailures                           = 92
    case expansionJointFailure                       = 93
    case fireOrExplosion                             = 94
    case lockingMechanismFailure                     = 95
    case internalSurfacesErosion                     = 96
    case weldsFatigue                                = 97
    case bearingRacewaysDeformation                  = 99
    case surfaceTreatmentsHardnessLoss               = 100
    case lubricantPumpFailure                        = 101
    case electrostaticDischargeDamage                = 102
    case improperAssembly                            = 103
    case galvanicCorrosion                           = 104
    case thermalCyclingFatigue                       = 105
    case improperAlignmentAfterMaintenance           = 106
    case foreignObjectDamage                         = 107
    case linerWear                                   = 108
    case suctionBlockage                             = 109
    case shaftDamage                                 = 110
    case suctionPressureLoss                         = 111
    case dischargePressureLoss                       = 112
    case housingLeak                                 = 113
    case incorrectVoltage                            = 114
    case electricalOverload                          = 115
    case damagedMechanicalSeal                       = 116
    case faultyShaftSeal                             = 117
    case casingLeak                                  = 118
    case suctionLineLeaks                            = 119
    case dischargeLineLeaks                          = 120
    case insufficientCoolingLiquidFlow               = 121
    case coolingSystemFailure                        = 122
    case impellerDirtBuildUp                         = 123
    
    // MARK: - Computed Properties
    
    /// Returns the key name as string (matching React Native enum keys)
    var keyName: String {
        switch self {
        case .none: return "None"
        case .imbalance: return "Imbalance"
        case .misalignment: return "Misalignment"
        case .looseness: return "Looseness"
        case .rotationalLooseness: return "RotationalLooseness"
        case .bearingWear: return "BearingWear"
        case .gearWear: return "GearWear"
        case .lubricantContamination: return "LubricantContamination"
        case .cavitation: return "Cavitation"
        case .impellerWear: return "ImpellerWear"
        case .rubbing: return "Rubbing"
        case .electrical: return "Electrical"
        case .resonance: return "Resonance"
        case .beltFailure: return "BeltFailure"
        case .chainFailure: return "ChainFailure"
        case .rotorProblem: return "RotorProblem"
        case .fatigueCracks: return "FatigueCracks"
        case .componentFracture: return "ComponentFracture"
        case .gearToothBreakage: return "GearToothBreakage"
        case .keywayFailure: return "KeywayFailure"
        case .bushingWear: return "BushingWear"
        case .couplingFailure: return "CouplingFailure"
        case .beltSlippage: return "BeltSlippage"
        case .gearboxOverheating: return "GearboxOverheating"
        case .rotorDamage: return "RotorDamage"
        case .sealLeakage: return "SealLeakage"
        case .structuralDeformation: return "StructuralDeformation"
        case .clutchWear: return "ClutchWear"
        case .pistonWear: return "PistonWear"
        case .valveSticking: return "ValveSticking"
        case .camshaftWear: return "CamshaftWear"
        case .highVibration: return "HighVibration"
        case .excessiveShockLoading: return "ExcessiveShockLoading"
        case .vibrationInducedLoosening: return "VibrationInducedLoosening"
        case .torsionalVibration: return "TorsionalVibration"
        case .axialVibration: return "AxialVibration"
        case .highTemperature: return "HighTemperature"
        case .overheating: return "Overheating"
        case .thermalExpansionIssues: return "ThermalExpansionIssues"
        case .thermalFatigue: return "ThermalFatigue"
        case .electricalComponentsInsulationDegradation: return "ElectricalComponentsInsulationDegradation"
        case .heatExchangerFouling: return "HeatExchangerFouling"
        case .lubricantDegradation: return "LubricantDegradation"
        case .insufficientLubrication: return "InsufficientLubrication"
        case .excessiveLubrication: return "ExcessiveLubrication"
        case .oilOxidation: return "OilOxidation"
        case .greaseClogging: return "GreaseClogging"
        case .lubricantLeaks: return "LubricantLeaks"
        case .electricalShortCircuits: return "ElectricalShortCircuits"
        case .insulationFailure: return "InsulationFailure"
        case .motorOverheating: return "MotorOverheating"
        case .powerSupplyFluctuations: return "PowerSupplyFluctuations"
        case .motorsBearingCurrentDamage: return "MotorsBearingCurrentDamage"
        case .circuitBoardFailure: return "CircuitBoardFailure"
        case .sensorMalfunction: return "SensorMalfunction"
        case .controlSystemFailures: return "ControlSystemFailures"
        case .corrosion: return "Corrosion"
        case .dustIngress: return "DustIngress"
        case .waterIngress: return "WaterIngress"
        case .chemicalAttack: return "ChemicalAttack"
        case .particulateContamination: return "ParticulateContamination"
        case .biologicalGrowth: return "BiologicalGrowth"
        case .contaminantsAbrasiveWear: return "ContaminantsAbrasiveWear"
        case .overloading: return "Overloading"
        case .underloading: return "Underloading"
        case .incorrectOperatingSpeed: return "IncorrectOperatingSpeed"
        case .improperStartupShutdownProcedures: return "ImproperStartupShutdownProcedures"
        case .frequentCycling: return "FrequentCycling"
        case .poorMaintenancePractices: return "PoorMaintenancePractices"
        case .materialCorrosion: return "MaterialCorrosion"
        case .brittleFracture: return "BrittleFracture"
        case .ductileFracture: return "DuctileFracture"
        case .creepDeformation: return "CreepDeformation"
        case .stressCorrosionCracking: return "StressCorrosionCracking"
        case .hydrogenEmbrittlement: return "HydrogenEmbrittlement"
        case .processVariations: return "ProcessVariations"
        case .inadequateProcessControl: return "InadequateProcessControl"
        case .thermalShock: return "ThermalShock"
        case .pressureSurges: return "PressureSurges"
        case .flowBlockages: return "FlowBlockages"
        case .pumpCasingCracks: return "PumpCasingCracks"
        case .fanBladeCracks: return "FanBladeCracks"
        case .millLiningWear: return "MillLiningWear"
        case .pressDieWear: return "PressDieWear"
        case .filterClogging: return "FilterClogging"
        case .valveSealFailure: return "ValveSealFailure"
        case .sensorDrift: return "SensorDrift"
        case .actuatorSticking: return "ActuatorSticking"
        case .controlSystemsSoftwareGlitches: return "ControlSystemsSoftwareGlitches"
        case .humanErrors: return "HumanErrors"
        case .improperCalibration: return "ImproperCalibration"
        case .vibrationInducedElectricalNoise: return "VibrationInducedElectricalNoise"
        case .resonantFrequencyChanges: return "ResonantFrequencyChanges"
        case .anchoringFailures: return "AnchoringFailures"
        case .expansionJointFailure: return "ExpansionJointFailure"
        case .fireOrExplosion: return "FireOrExplosion"
        case .lockingMechanismFailure: return "LockingMechanismFailure"
        case .internalSurfacesErosion: return "InternalSurfacesErosion"
        case .weldsFatigue: return "WeldsFatigue"
        case .bearingRacewaysDeformation: return "BearingRacewaysDeformation"
        case .surfaceTreatmentsHardnessLoss: return "SurfaceTreatmentsHardnessLoss"
        case .lubricantPumpFailure: return "LubricantPumpFailure"
        case .electrostaticDischargeDamage: return "ElectrostaticDischargeDamage"
        case .improperAssembly: return "ImproperAssembly"
        case .galvanicCorrosion: return "GalvanicCorrosion"
        case .thermalCyclingFatigue: return "ThermalCyclingFatigue"
        case .improperAlignmentAfterMaintenance: return "ImproperAlignmentAfterMaintenance"
        case .foreignObjectDamage: return "ForeignObjectDamage"
        case .linerWear: return "LinerWear"
        case .suctionBlockage: return "SuctionBlockage"
        case .shaftDamage: return "ShaftDamage"
        case .suctionPressureLoss: return "SuctionPressureLoss"
        case .dischargePressureLoss: return "DischargePressureLoss"
        case .housingLeak: return "HousingLeak"
        case .incorrectVoltage: return "IncorrectVoltage"
        case .electricalOverload: return "ElectricalOverload"
        case .damagedMechanicalSeal: return "DamagedMechanicalSeal"
        case .faultyShaftSeal: return "FaultyShaftSeal"
        case .casingLeak: return "CasingLeak"
        case .suctionLineLeaks: return "SuctionLineLeaks"
        case .dischargeLineLeaks: return "DischargeLineLeaks"
        case .insufficientCoolingLiquidFlow: return "InsufficientCoolingLiquidFlow"
        case .coolingSystemFailure: return "CoolingSystemFailure"
        case .impellerDirtBuildUp: return "ImpellerDirtBuildUp"
        }
    }
    
    // MARK: - Static Methods
    
    /// Get FailureType from raw value with fallback to .none
    static func from(rawValue: Int) -> FailureTypes {
        return FailureTypes(rawValue: rawValue) ?? .none
    }
}
